[package]
name = "bcndecode"
version = "0.1.0"
authors = ["Istvan Fehervari <gooksl@gmail.com>", "Robert Nix <mischanix@gmail.com>"]
description = "Decoder for DXTn-compressed image data."
license = "MIT"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2.26"
